[package]
description = "Rust bindings for tinykeccak C library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "hash"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[dependencies]
ethcore-bigint = { path = "../bigint" }
tiny-keccak = "1.3"

[build-dependencies]
gcc = "0.3"

[dev-dependencies]
tempdir = "0.3"
