version: 2
jobs:
  build:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Install deps
          command: apt install pkg-config libssl-dev libudev-dev
      - run:
          name: Build parity
          command: cargo build --release
