[package]
description = "Ethcore blockchain sync"
name = "ethsync"
version = "1.8.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[lib]

[build-dependencies]
ethcore-ipc-codegen = { path = "../ipc/codegen" }

[dependencies]
ethcore-util = { path = "../util" }
ethcore-bytes = { path = "../util/bytes" }
ethcore-bigint = { path = "../util/bigint" }
ethcore-network = { path = "../util/network" }
ethcore-io = { path = "../util/io" }
ethcore-light = { path = "../ethcore/light"}
ethcore = { path = "../ethcore" }
rlp = { path = "../util/rlp" }
hash = { path = "../util/hash" }
triehash = { path = "../util/triehash" }
kvdb = { path = "../util/kvdb" }
macros = { path = "../util/macros" }
clippy = { version = "0.0.103", optional = true}
log = "0.3"
env_logger = "0.4"
time = "0.1.34"
rand = "0.3.13"
heapsize = "0.4"
ethcore-ipc = { path = "../ipc/rpc" }
semver = "0.6"
smallvec = { version = "0.4", features = ["heapsizeof"] }
ethcore-ipc-nano = { path = "../ipc/nano" }
ethcore-devtools = { path = "../devtools" }
ethkey = { path = "../ethkey" }
parking_lot = "0.4"
ipnetwork = "0.12.6"

[features]
default = []
dev = ["clippy", "ethcore/dev", "ethcore-util/dev"]
ipc = ["ethcore-light/ipc"]
